### ISSUE TITLE
IPV6 Support for Nextcloud Security Scanner

### ISSUE THREAD

**Issue by Brakelmann** [nextcloud/nextcloud.com#1033]
Feature request for IPV6 support for the Nextcloud Security Scanner.

**Comment by tflidd** [comment]
Why not ipv6 on the whole infrastructure?
I used virtual servers in the past for testing Nextcloud. It was easier to set up with ownCloud in the past because all resources are available via ipv6, and there is no need to set up special ipv4 routing or NAT.

**Comment by Brakelmann** [comment]
> Why not ipv6 on the whole infrastructure? 
Mh maybe I don't get your comment correctly.

Nextcloud does support IPV6 and dual stack. My System is running as ipv6 in my infrastructure this is not a problem. 
The issues is that Security Scanner is not able to scan IPV6 systems.

**Comment by tflidd** [comment]
> Nextcloud does support IPV6 and dual stack. My System is running as ipv6 in my infrastructure this is not a problem.

I mean all the servers and services from nextcloud, the app store, download page, homepage, forum, ...

**Comment by MariusBluem** [comment]
Our infrastructure team is aware of IPv6 and we are constantly improving our servers regarding stability and performance. I will close this ticket over here since this issue tracker is only for our homepage **nextcloud.com** but not for our other systems (such as our scan.nextcloud.com). But I'll promise to track this internally.

**Comment by sreith1** [comment]
Are there any news on that? Since IPv4 address space is getting scarce, this is getting increasingly important.

**Comment by No0ne** [comment]
This seems to be still an issue in 2022 :(
