### ISSUE TITLE
so many warnnings on php 7.3 and wordpress 5.2

### ISSUE THREAD

**Issue by banditsmile** [nextcloud/nextcloud.com#1109]
environment:
os: CentOS Linux release 7.6.1810 (Core)
php: 7.3
wordpress:5.2
nextcloud.com path: /home/bandit/download/github/nextcloud/next
wordpress root:/data/www/nextcloud.series.ink
url:https://nextcloud.series.ink  

some of all the warnings:

Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; Recent_Docs has a deprecated constructor in /home/bandit/download/github/nextcloud/next/lib/recentdocswidget.php on line 6

Deprecated: Function create_function() is deprecated in /home/bandit/download/github/nextcloud/next/lib/recentdocswidget.php on line 4

Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; Recent_Blog_Posts has a deprecated constructor in /home/bandit/download/github/nextcloud/next/lib/recentblogswidget.php on line 7

Deprecated: Function create_function() is deprecated in /home/bandit/download/github/nextcloud/next/lib/recentblogswidget.php on line 5

Notice: 在Roots_Vcard_Widget中为WP_Widget调用的构造函数已自版本4.3.0起废弃！请改用
__construct()
。 in /data/www/nextcloud.series.ink/wp-includes/functions.php on line 4503

Notice: 在Recent_Docs中为WP_Widget调用的构造函数已自版本4.3.0起废弃！请改用
__construct()
。 in /data/www/nextcloud.series.ink/wp-includes/functions.php on line 4503

Notice: 在Recent_Blog_Posts中为WP_Widget调用的构造函数已自版本4.3.0起废弃！请改用
__construct()
。 in /data/www/nextcloud.series.ink/wp-includes/functions.php on line 4503

![nextcloud series ink_](https://user-images.githubusercontent.com/2239356/57675945-ebb02c80-7655-11e9-878f-2f494bc7d66b.png)

**Comment by tflidd** [comment]
You are probably at the wrong repository here. This is for the nextcloud.com homepage only. Your problem seems to be more related about an installation of Nextcloud. A good starting point is the forum on help.nextcloud.com, in case you have identified a bug you can post a bug on https://github.com/nextcloud/server/issues.

Don't install Nextcloud directly from the github-repo, except for development:
https://docs.nextcloud.com/server/16/developer_manual/general/devenv.html

Use this guide for all other setups:
https://docs.nextcloud.com/server/16/admin_manual/installation/index.html
