### ISSUE TITLE
Enterprise page

### ISSUE THREAD

**Issue by oparoz** [nextcloud/nextcloud.com#150]
We need a separate place to discuss and validate the enterprise page before it goes live.

Current issues:

- [ ] Plans table has wrong information
- [ ] "Buy it" should be renamed, maybe to "Pricing"
- [ ] Missing Pricing page

**Comment by Espina2** [comment]
@oparoz What is the Pricing page nowadays?

**Comment by oparoz** [comment]
Well, there isn't one. The prices are included in the "Plans table". Apparently, it's been decided to go through a separate page and I don't really know if that will work, because people will then see prices without the features of the plan, but it will have to be created from scratch.

**Comment by Espina2** [comment]
https://nextcloud.com/enterprise/?staging=true

If you see you have the price in the top of the table. Now you only dont have a hidden table to do math for you. The think that Im going to design is something like the contact form but with more information and in clever way (not a regular form). 

Doesn't matter to have the precise price because they all having to contact and if I am right they have to pay more than subscription.

**Comment by oparoz** [comment]
> Doesn't matter to have the precise price because they all having to contact and if I am right they have to pay more than subscription.

Actually, we get quite a few requests asking for the cost for x users, so what we would really need is an online calculator to give decision makers an idea of the cost, but what we currently have at the bottom of the plans would work in the mean time. In any case, we haven't decided to hide the prices yet, so they need to be on that page until we decide otherwise.

**Comment by LukasReschke** [comment]
@oparoz Clicking on buy opens https://github.com/nextcloud/nextcloud.com/blob/staging/page-buy.php.

**Comment by oparoz** [comment]
Thank you @LukasReschke!

**Comment by Espina2** [comment]
This is already fixed.
