### ISSUE TITLE
Security scan reports version 22.1.0.1 as "NOT latest patch level"

### ISSUE THREAD

**Issue by arnowelzel** [nextcloud/nextcloud.com#1530]
https://scan.nextcloud.com reports Nextcloud 22.1.0.1 as "NOT on latest patch level" - however this is wrong, there is no newer version at the moment.

![image](https://user-images.githubusercontent.com/6613614/129471848-f6499fb4-f2e2-41ea-ac57-3eb95f8a2da7.png)

Also see https://download.nextcloud.com/server/releases/ - the latest version is https://download.nextcloud.com/server/releases/latest-22.zip, dated 2021-08-04, and identifies as 22.1.0.1 in `version.php`:

```
<?php
$OC_Version = array(22,1,0,1);
$OC_VersionString = '22.1.0';
```

**Comment by Meuschke23** [comment]
i have this problem too.

![grafik](https://user-images.githubusercontent.com/65863113/129870500-fbac5e65-a343-4596-a361-472a70cb5d9c.png)

![grafik](https://user-images.githubusercontent.com/65863113/129870570-62d26000-f36e-4f6b-b357-80b1cb9085a4.png)

**Comment by fabioleite0** [comment]
same here!

**Comment by BartG95** [comment]
I have the same problem, currently with 22.1.1.2. Double-checked for updates.

Before I had this issue, I was on the latest patch of v21 and my update channel was stable.
Just before v22 was officially released, I switched to beta channel to update to the latest rc of v22.
Since that update I have this issue.
Right after the update, I switched to stable channel, and since then I followed all updates.
In the meantime, I tried switching to the beta channel, to see if there was a newer patch level available, but each time I saw no new version on the beta channel, so each time I switched back to the stable channel.

btw, this issue is a duplicate of #1535

**Comment by arnowelzel** [comment]
The same happens here with 22.1.1.2 too:

![image](https://user-images.githubusercontent.com/6613614/132105020-edd1e007-6dff-4bf4-bab1-2088dddfb927.png)

What can we do to help here?

**Comment by arnowelzel** [comment]
It would also help, if the scanner would tell us which version it sees as the latest patch level like this:

"NOT on the latest patch level (x.x.x.x)"

Then we know at least what the scanner expects.

**Comment by arnowelzel** [comment]
Eventhough you closed it - the issue is still present. At the moment 22.1.1.2 is the latest version available (see https://download.nextcloud.com/server/releases/nextcloud-22.1.1.zip). However - the security scan still says "NOT on the latest patch level" and it still does not tell us, which patch level it expects as "latest":

![image](https://user-images.githubusercontent.com/6613614/132674247-11e6b211-05c0-4836-b778-ef06cafd0816.png)

**Comment by blizzz** [comment]
@szaimen could you double-check? I get can confirm.

**Comment by szaimen** [comment]
Can confirm, too. Not sure why it doesn't work, though...

**Comment by szaimen** [comment]
Should be fixed now :)

**Comment by blizzz** [comment]
My bad, deployed wrongly, sorry @szaimen. Fixed now.

**Comment by szaimen** [comment]
all good! Thanks for fixing :)

**Comment by arnowelzel** [comment]
I can confirm that it works now - thanks!
