### ISSUE TITLE
Team / Contributors

### ISSUE THREAD

**Issue by mar1u5** [nextcloud/nextcloud.com#18]
I think we should create an team/contributors-page where we show profile pictures and maybe some information about the guys at @Nextcloud 😉 (maybe sorted by teams)

cc @karlitschek @jospoortvliet

**Comment by karlitschek** [comment]
Great idea. But I think this is something where contribook could be used for. @jospoortvliet

**Comment by jospoortvliet** [comment]
There's some work for that prepared already, will absolutely move on that but - later. Backlog ;-)

**Comment by ldonis** [comment]
For the contributor section we can use the github api to get the members information (user, picture, commits, etc. etc.) also we can sort the list according to the commits to the project.
If you have more commits, then you will be at the top of the contributor list in the website.

**Comment by jospoortvliet** [comment]
We shouldn't order by anything other than alphabet or so, simply because there isn't a single metric which shows how important somebody is ;-)

**Comment by ldonis** [comment]
@jancborchardt you're right,
@jospoortvliet good idea!

**Comment by jancborchardt** [comment]
That’s why lots of projects simply randomize the contributor order on every page load, and that is the reasonable thing to do. Alphabetic sorting also gives order, and even though it’s arbitrary, outside people don’t know that and assume it’s sorted by importance.

**Comment by ldonis** [comment]
@jancborchardt it is clear now :( , thanks a lot for the explanation!!!!
so, let's start to work, I'm not a good designer (I can see only two colors, gray and dark-gray) but, I can code any psd or any design that you can provide me.
also, it could be a completely new webpage ?? (http://nextcloud.com/contributors for example)

**Comment by jancborchardt** [comment]
@ldonis awesome, exactly the people we need! :)

I think the team page of [Ghost](https://ghost.org/team/) is one of the best around. Instead of the join date, below the name I would have 3 icons there maybe: website, Github, Twitter.
What do you think @jospoortvliet @karlitschek?

**Comment by jospoortvliet** [comment]
If you randomize on every page load, each time people will think it is ordered in importance or something (they don't reload and see if things change). If you do it alphabetically it is obvious right away that it is ordered on alphabet and done.

**Comment by jospoortvliet** [comment]
Now with regards to actually doing this. ownCloud just published and tweeted around a team page which includes their employees and people at external contractors, I guess to try and look stable and big to customers and such.

Now imagine what happens if we would also put up a page with faces, especially with *more* people, because we put community there rather than management and employees, sorted by 'importance'. The current Nextcloud repo has already well over 60 people...

Now that would probably make them feel it is a response, a "my penis is longer" thing, making people angry and all that. And what's next? They respond by putting up the 300+ members from the ownCloud github repo, trying to create a twitter war and making many of *those* angry in return as they no longer want to be part of ownCloud, others haven't been active for ages etc etc etc. Lots of mess, lots of fighting.

To avoid that drama, let's wait some weeks with this, shall we? Yes, I also want to give credit where it is due and put something up that does it but now clearly isn't the time, even if we wanted to do this before they did it and even if we just want to do the right thing here. That just doesn't matter.

In some weeks people will hopefully have calmed down a bit and we can put up a nice page giving community credit where it is due without creating an unwanted pissing contest.

**Comment by jospoortvliet** [comment]
however, that doesn't mean we can't work on it, @ldonis it'd be cool to prepare this! @LukasReschke proposed to run a script to add info from people in our github project to contribook and then we can show them quite easily.

If you look at page-contact.php, you see the commented out contribook part. That is what would do this - show people from there. Making that look nice, like the ghost page, would rock ;-)

**Comment by jancborchardt** [comment]
Another great example of a team page next to Ghost is Ginetta: http://ginetta.net/index.html#members

**Comment by ldonis** [comment]
@jancborchardt you're good for inspiration, I am going to start to write some code.
I am excited to work with you guys!

**Comment by jospoortvliet** [comment]
That page is, indeed, awesome. Look forward to your first PR, @ldonis ;-)

**Comment by jospoortvliet** [comment]
So I'm thinking we should move on this, it's been two weeks. @ldonis did you find time for this? Then I'll talk to @LukasReschke about syncing the data from github to our database... Pages like https://nextcloud.com/user/?user=FrankKarlitschek work and will then have all ppl in our project.

**Comment by mar1u5** [comment]
https://nextcloud.com/contributors/
