### ISSUE TITLE
Site but pick

### ISSUE THREAD

**Issue by thefirstofthe300** [nextcloud/nextcloud.com#20]
On my Nexus 5X.

![screenshot](https://owncloud.danielseymour.info/s/Gz3OMgEr1oAdQOf/download)

**Comment by thefirstofthe300** [comment]
Sorry about it being so big. I.submitted this from my phone. Give me a couple of hours and I will shrink it.

**Comment by mikebabb** [comment]
I have a fix for this in [PR 19](https://github.com/nextcloud/nextcloud.com/pull/19). Giving the hangouts graphic a static size at various media queries instead of a percentage stops its height being recalculated when the mobile menu is open, which is what is causing the graphic to "grow" and obscure content in some circumstances.
