### ISSUE TITLE
All the buttons have a different arrow

### ISSUE THREAD

**Issue by Espina2** [nextcloud/nextcloud.com#208]
![screen shot 2016-10-18 at 20 41 57](https://cloud.githubusercontent.com/assets/11150206/19494075/4aa1b1ec-9575-11e6-92a0-f37322d3bc9a.png)

This arrow is weird? What happens to the previous one?

**Comment by Espina2** [comment]
@jospoortvliet @LukasReschke

**Comment by jospoortvliet** [comment]
what? This was on the main page initially and due to some css change (no clue who did it, the fun of including css files through dependencies) is now on every page. I think it looks ok but what is your question?

**Comment by Espina2** [comment]
![screen shot 2016-10-24 at 11 11 15](https://cloud.githubusercontent.com/assets/11150206/19641889/997d8dcc-99da-11e6-8f3c-4a0896da013d.png)

This should be the default arrow. The problem here is not the css is the file is modified an replaced because of that. I think its when you optimize img that this are changed. The svg file is below

[arrow-right.svg.zip](https://github.com/nextcloud/nextcloud.com/files/547446/arrow-right.svg.zip)

**Comment by LukasReschke** [comment]
> what? This was on the main page initially and due to some css change (no clue who did it, the fun of including css files through dependencies) is now on every page. I think it looks ok but what is your question?

No. This is due to some strange image optimisation tool that somebody ran so we can save amazeball 23kb or so … Because that is exactly what will make our website faster ;)

You broke it with your image optimization tool. See https://github.com/nextcloud/nextcloud.com/commits/32806526260eaed08f77fe6674114dee151e6c23/assets/img/arrow_right.svg for the before / after and then afterwards some other random SVG was used instead 😉

**Comment by Espina2** [comment]
Fixed here, https://github.com/nextcloud/nextcloud.com/pull/247
