### ISSUE TITLE
Jobs page - clicking "account manager" redirects to install page

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/nextcloud.com#292]
* Chrome on macOS
* clicking the account manager heading I got redirected to the install page
* clicking all the other jobs they properly fold out

cc @Espina2 @jospoortvliet

**Comment by MorrisJobke** [comment]
> clicking the account manager heading I got redirected to the install page

Maybe also try to double click ... It happens for me if I double click on mobile (maybe because the entry for "download" is on the same location when I click on the menu button - seems to be not properly hidden somehow)

**Comment by jospoortvliet** [comment]
argh yeah you can get random pages loaded. Must be indeed an issue with the new header javascript code not actually hiding the links completely enough. I sadly don't have even the beginnings of a clue on where to look to fix this. @Espina2 might have a pointer.


... and then looking into it more... Found a solution in CSS. Because that, at least, I can do :dagger: 
https://github.com/nextcloud/nextcloud.com/commit/b619f6c6f83ab2765ce7ade03e9db6d5615d6840

please test, I've put it live.

**Comment by Espina2** [comment]
I already fix that in the cross-browser PR. And its because what @MorrisJobke said. I will fix this later. Anyway I test it live, and I don't have this bug. Can you please do a hard refresh to the page?

If it not works properly after hard refresh please let me know.

**Comment by MorrisJobke** [comment]
Tested and works after a hard refresh now 👍
