### ISSUE TITLE
Header Issues with Safari

### ISSUE THREAD

**Issue by MariusBluem** [nextcloud/nextcloud.com#389]
![bildschirmfoto 2017-02-03 um 23 00 04](https://cloud.githubusercontent.com/assets/19711361/22610235/c46fb3d6-ea64-11e6-85fa-11f780c3db72.png)

![bildschirmfoto 2017-02-03 um 22 59 58](https://cloud.githubusercontent.com/assets/19711361/22610238/c9d19272-ea64-11e6-94fc-fa817cbc43ea.png)

...seems to be a Safari-issue 🤔 
@Espina2

**Comment by Espina2** [comment]
Just happens in safari?

**Comment by MariusBluem** [comment]
Jup ... also Header Issue not fixed for Safari 😞

**Comment by MariusBluem** [comment]
Also on mobile ... the menu is not longer visible for Safari 😢

**Comment by Espina2** [comment]
No problens here. Tested in safari 10.0.3 . Can you please try first a hard reset, or open a private tab and see if the error persist?

**Comment by MariusBluem** [comment]
Okay ... Just resetted my browser, still having the following issues:

- [ ] Menu placed wrong: Happens sometimes (seems to be Safari-only)

![bildschirmfoto 2017-02-06 um 14 03 34](https://cloud.githubusercontent.com/assets/19711361/22648152/8a015426-ec75-11e6-9392-1c9df05e6b6e.png)

- [ ] Fonts are too small in mobile-menu (Tested with Safari, IDK for other browsers)

![bildschirmfoto 2017-02-06 um 14 04 31](https://cloud.githubusercontent.com/assets/19711361/22648189/bc66980e-ec75-11e6-8a3a-fdfd1527aa99.png)

- [ ] Old header bug still happens for some pages (e.g. Code of Conduct) - Download is fixed now 👍 

![bildschirmfoto 2017-02-06 um 14 02 42](https://cloud.githubusercontent.com/assets/19711361/22648202/cedc6414-ec75-11e6-9ba7-23e7df541839.png)

- [ ] Header is not there (happens to my cleaned iOS device - Safari) 😢 

![img_2482](https://cloud.githubusercontent.com/assets/19711361/22648252/0c7dfa94-ec76-11e6-8dca-c44dbc90978e.PNG)

...easiest thing would be an message-box with the text "Safari is not supported by Nextcloud.com - Please try a different browser" 😜😜

**Comment by Espina2** [comment]
Its difficult to track the bugs with the safari since most all that you point I don't have it in mine. 

![screen shot 2017-02-07 at 10 54 38](https://cloud.githubusercontent.com/assets/11150206/22688362/dd783788-ed23-11e6-83e1-a71201ee260c.png)

The fonts of menu are ok to me. 

![screen shot 2017-02-07 at 10 55 39](https://cloud.githubusercontent.com/assets/11150206/22688387/fe8c892e-ed23-11e6-9b8a-e9dd2402443f.png)

This should not happen, you should update your browser more often. :p

**Comment by Espina2** [comment]
In mobile I have the same error than you, but I can figure yet what is the problem
![screen shot 2017-02-07 at 11 04 02](https://cloud.githubusercontent.com/assets/11150206/22688673/30261b34-ed25-11e6-956b-698ff6fef713.png)

**Comment by jacboy** [comment]
Sorry for close and re open of the issue, was a mistake by mobile. 

When I visit the enterprise page on my iPhone it also seems to be a little bit too tight for the new type of menu. I can't attach a screenshot here because I obly got my iPhone for now, but take a look at this. 

http://i.imgur.com/RY8svpD.jpg

**Comment by jospoortvliet** [comment]
The menu should be hidden on small screens but that doesn't seem to work. Sadly, this is handled in Javascript so I can't figure out how/what/where. @Espina2 can you have a look?

**Comment by jospoortvliet** [comment]
I did fix the issue with the image being too light so text doesn't show on it.

**Comment by Espina2** [comment]
If I can understand what is the problem maybe I can fix it. :p

**Comment by jospoortvliet** [comment]
Is this fixed now? Please re-open if not...
