### ISSUE TITLE
add app image download option

### ISSUE THREAD

**Issue by jospoortvliet** [nextcloud/nextcloud.com#426]
Add the appimage to download page, see
https://twitter.com/probonopd/status/840270164792872961

**Comment by probonopd** [comment]
As pointed out in https://github.com/nextcloud/client_theming/issues/61:

Right now an [AppImage](http://appimage.org/) for Linux is produced for each commit on Travis CI and can be downloaded from a temporary transfer.sh URL that is visible toward the end of each [Travis CI build log](https://travis-ci.org/nextcloud/client_theming/). Few people will ever find it there.

Hence, build an AppImage for the stable release and link it on the [download page](https://nextcloud.com/install/#install-clients) instead of "Source":

![](https://lh3.googleusercontent.com/H0Cf0F-5FJZ21IHbGZMfnxx6iarglCfFlStZjQ-yNqmkyGpqiqV9YfE18MN48pzrr3J3CBTO3DWQbA=w717-h544-no)

Providing an [AppImage](http://appimage.org/) has, among others, these advantages:
- Works for most Linux distributions (including Ubuntu, Fedora, openSUSE, CentOS, elementaryOS, Linux Mint, and others). The version that gets built on Travis CI should run on 2014-ish and later distributions
- One app = one file = super simple for users: just download one AppImage file, [make it executable](http://discourse.appimage.org/t/how-to-make-an-appimage-executable/80), and run
- No unpacking or installation necessary
- No root needed
- No system libraries changed
- Just one format for all major distributions
- Works out of the box, no installation of runtimes needed (unlike Snap and Flatpak)
- Optional desktop integration with `appimaged`
- Optional binary delta updates, e.g., for continuous builds (only download the binary diff) using AppImageUpdate
- Can optionally GPG2-sign your AppImages (inside the file)
- Works on Live ISOs (unlike Flatpak)
- Can use the same AppImages when dual-booting multiple distributions

**Comment by probonopd** [comment]
Edited the above ^^^

**Comment by MariusBluem** [comment]
Makes a lot of sense ... lets wait until the new install page is ready (#434) - otherwise we will do this twice 😅🙈

**Comment by m4lvin** [comment]
The button is there now but with both Firefox 52.3 and Chromium 60 clicking on it loads plain text garbage into the browser instead of downloading a file. Apparently the server from which the AppImage is downloaded does not send correct HTTP headers to indicate that this is a binary file meant to be downloaded and not displayed?

**Comment by jospoortvliet** [comment]
wow, yes, can reproduce. Will fix a bug internally with sysadmin about our download server. Thanks for noticing!

**Comment by m4lvin** [comment]
Thanks for the quick reply.

Where should bugs in the AppImage itself be reported? On Debian 9 Stretch I ran into ` "error creating ssl context (error:140A90C4:SSL routines:func(169):reason(196))"` as described here https://help.nextcloud.com/t/nextcloud-client-appimage-version-2-3-2-ssl-problem/19870

**Comment by jospoortvliet** [comment]
@m4lvin pls use the client_theming repo for now... https://github.com/nextcloud/client_theming

Thanks!

Meanwhile, this was fixed, so let's close.
