### ISSUE TITLE
when you scroll to a # it might not show anything

### ISSUE THREAD

**Issue by jospoortvliet** [nextcloud/nextcloud.com#502]
https://nextcloud.com/sharing/#federation gives me a nearly empty page due to the 'appear on scroll' javascript...

**Comment by Espina2** [comment]
Its normal to behaviour like that. And there is no problem with that. You should not use the links with anchor part.

**Comment by jospoortvliet** [comment]
Well, then, how do I link to a specific section in a page from a blog or the forums or somewhere else if not via this? I have to do that, as I need to point people to the federation part of the sharing page...

**Comment by Espina2** [comment]
@jospoortvliet how you point people if the anchors doesn't exist? They are not created with that purpose, but yes for the purpose when you click on a button scroll to that area. So the problem is not directly involved by the "appear" transition. Remenber that this stuff is added for the submenu work...

We can of course fix this is problem with some window position validation, for example 

var currentScrollPosition = document.documentElement.scrollTop || document.body.scrollTop;

If (currentScrollPosition <= 100) {
autorun reveal on scroll
}

**Comment by jospoortvliet** [comment]
@Espina2 I don't understand - what do you mean with "if the anchors doesn't exist"? They DO exist, like the example I give... Sometimes there are buttons that go there but not always. I prefer to link directly to a sub section of a page instead of telling people 'go to this page and scroll down'...

**Comment by Espina2** [comment]
@jospoortvliet what I am trying to say is when the anchors are introduced in those pages is not for that purpose. Anyway I fix the issue here https://github.com/nextcloud/nextcloud.com/pull/505
