### ISSUE TITLE
An old Nextcloud version number is shown on the localized German download page

### ISSUE THREAD

**Issue by j-ed** [nextcloud/nextcloud.com#558]
Different Nextcloud version numbers are shown on the following web pages:

https://nextcloud.com/de/install/#instructions-server -> 11.0.2 (*1)
https://nextcloud.com/install/#instructions-server -> 12.0.2

*1 - https://nextcloud.com/de/team/ -> Download -> Download

**Comment by j-ed** [comment]
The problem still exists for the first URL but the second URL has been fixed and currently shows `12.0.3` .

**Comment by mathiasconradt** [comment]
I think the German version of the website hasn't officially been launched yet and therefore should actually not appear in search engines, but somehow still pops up.

@jospoortvliet Any way to disable the German version entirely at the moment so that search engines don't index them. Cause I still get results for /de/

![screen shot 2017-11-10 at 09 03 04](https://user-images.githubusercontent.com/295122/32648508-56c07dac-c5f6-11e7-88fd-e689ea90d0dd.png)

(I had another user contacting me via Nextcloud contact form and was reporting this same issue today 10.11.2017: "The German page https://nextcloud.com/de/install/ still links to version 11 of user and admin manuals, even though v 12 is also available. I guess you might want to update the links.")

**Comment by jospoortvliet** [comment]
The pages are now up-to-date and we'll keep them updated.
