### ISSUE TITLE
Add Bullet points

### ISSUE THREAD

**Issue by MariusBluem** [nextcloud/nextcloud.com#715]
I know we had this discussion some time ago already, but we have now many places where bullet points would make sense... can we please reintroduce them? They are missing at some places :( 

@Espina2 @jospoortvliet

**Comment by jospoortvliet** [comment]
It's a design decison so - I'm staying out. For the record, @camilasan and others have also noted it looks better without so... I guess it's just for old-fashioned people like you and me, Marius, that we miss our bullets.

**Comment by tflidd** [comment]
I reviewed a PR where I was missing the bullet points and was surprised to hear that they don't look nice. Can't you make them look nice? It doesn't have to be a big clumsy point but without it, I read through it and my reading flow is interrupted until I recognize it should be a list and then I'm wondering why the bullet points are missing. Putting a symbol in front is just a convention (old-fashioned people like that). You won't change the writing from right to left just because it looks nicer.

Example:
Look at this page at the accepted feature loss: https://nextcloud.com/endtoend/

And on some pages you have listings:
https://nextcloud.com/pricing/

**Comment by jospoortvliet** [comment]
I have now used V marks in quite a bunch of places. Better?

If it is bad in some pages still, let me know, I will put the check marks in. I can even do it site-wide...

**Comment by tflidd** [comment]
> I have now used V marks in quite a bunch of places. Better?

:+1:
