### ISSUE TITLE
Content only loads after scrolling

### ISSUE THREAD

**Issue by tflidd** [nextcloud/nextcloud.com#775]
On FF 58.0.1 and Chrome 63.0.3239.132 (Official Build) (64-bit) on Windows 10, the pages of Nextcloud.com only show the page header by default. The content is only loader after I start to scroll that's a weird experience.

I submitted some snapshots here:
https://github.com/nextcloud/nextcloud.com/pull/770#issuecomment-362224780

**Comment by splitt3r** [comment]
Another good example is https://nextcloud.com/error404 the footer won´t load until you scroll (but most of the screens are big enough so that there is no scrollbar).

**Comment by jospoortvliet** [comment]
This is intentional - due to the javascript effect thingy  added to the website by @Espina2 

I generally try to make sure the very first element of the page doesn't have this "revealOnScroll" added, but on some pages I made a mistake. You can look in the source of the page and remove the reveal-on-scroll class from the items that should show on page load to fix it - quite easy, just edit the source online and make a PR ;-)

**Comment by jasonbayton** [comment]
I can see there is an ongoing project to move to hugo, which might be the best course of action given the bespoke approach you take to publishing pages in wordpress, if this weren't the case I'd be looking at setting up a project to comb through this content and make it a little easier to manage.

Generally not a fan of the effect either.

**Comment by jospoortvliet** [comment]
Yeah, in the end it's a design decision I don't want to interfere with... :cry:
