### ISSUE TITLE
Make provider list random

### ISSUE THREAD

**Issue by jospoortvliet** [nextcloud/nextcloud.com#84]
The providers are now shown in order they were added. This isn't really fair for those who've been supporting our project for years but just took longer to migrate to Nextcloud. Ideally, we order somehow on 'quality' but that is super hard to determine objectively...

So, as a measure until we have a better solution, how about ordering them randomly? It probably won't be hard to implement for somebody who knows a bit of jquery but that just isn't me ;-)

So, help welcome.

**Comment by jancborchardt** [comment]
cc @Gomez @pierreozoux @owndrive since they are providers.

And just for the record if we decide to sort them somehow, a list of potential criteria we discussed about before is at https://github.com/owncloud/owncloud.org/pull/525#issuecomment-94007215
And another one at https://github.com/nextcloud/android/issues/53#issuecomment-229081490

**Comment by Gomez** [comment]
Thanks for putting all infos in this ticket. 

As long as we don't have a sorting in place, random is better.

**Comment by LukasReschke** [comment]
Done and live at https://nextcloud.com/providers/
