### ISSUE TITLE
Blog page. Images in the header are too big

### ISSUE THREAD

**Issue by Spartachetto** [nextcloud/nextcloud.com#977]
I am getting this problem from some time, now it is getting worse.

I'll try to describe it, now I cannot attach images.

Browser Firefox on different computers (at least 2). OS: Windows, one is Windows 7 professional

Blog page. The header has three blue images that are too big:
A pencil (https://Nextcloud.com/signup)
A "power" button (https://Nextcloud.com/devices)
A phone (https://Nextcloud.com/install/#install-clients)

Now the phone image partly covers the first article of the blog.

The background of the images is transparent, yet on hovering I get a big white background that covers also the first line of articles.

The problem is really disturbing @jospoortvliet

**Comment by jospoortvliet** [comment]
This is probably due to old CSS cached in your browser. Try holding shift and pressing the refresh button, most browsers then clear the cache. Or use the developer tools ('inspect') and reload. It should resolve it.

I will try some trick to force cleaning the cache, but that doesn't always work I've noticed :(

**Comment by jospoortvliet** [comment]
Hopefully this fixes it: https://github.com/nextcloud/nextcloud.com/commit/e51ca94fbe6c523264355af68c28175c9c2de26f

**Comment by Spartachetto** [comment]
I confirm that I do not have this problem anymore. Thank you @jospoortvliet !
