### ISSUE TITLE
 More options and more clients do not work on the download page

### ISSUE THREAD

**Issue by thelinuxfr** [nextcloud/nextcloud.com#99]
Hi,

The popovers "more options" and "more clients" do not work on the download page (https://nextcloud.com/install/).

Tested on Firefox and Safari

Thx

**Comment by mar1u5** [comment]
I can reproduce this. This has worked in the past :scream: 

cc @jospoortvliet

**Comment by mar1u5** [comment]
"More Options" is also not clickable :scream: ... I think the install_instructions are not live :grin:

**Comment by jospoortvliet** [comment]
problem is in 
https://github.com/nextcloud/nextcloud.com/commit/dbe798eaab525663326cd304290473900da7041e

trying to fix now..

**Comment by jospoortvliet** [comment]
So I tried to include the install_instructions https://github.com/nextcloud/nextcloud.com/commit/dd9d05491cbea72fa3bf14db51f8469a884f271c which kind of worked once, locally, but then broke again (?!?! wtf PHP!) and then I looked at the PHP output which told me:

```
[Tue Aug  9 10:07:42 2016] PHP Parse error:  syntax error, unexpected ':', expecting ',' or ';' in /home/jospoortvliet/source/nextcloud.com/install-instructions.php on line 183
[Tue Aug  9 10:07:42 2016] ::1:47056 [200]: /install/ - syntax error, unexpected ':', expecting ',' or ';' in /home/jospoortvliet/source/nextcloud.com/install-instructions.php on line 183
[Tue Aug  9 10:08:08 2016] ::1:47058 Invalid request (Unexpected EOF)
```

So the fix turned out to be: https://github.com/nextcloud/nextcloud.com/commit/4437c5d51e015b89a1189f6b2587ed37572c3893

...

all good now.  ;-)
